insert into suggestions (sugId, description, therapistId, userId) values (10001, 'eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 101, 1);
insert into suggestions (sugId, description, therapistId, userId) values (10002, null, null, 2);
insert into suggestions (sugId, description, therapistId, userId) values (10003, 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce', 103, 3);
insert into suggestions (sugId, description, therapistId, userId) values (10004, null, 104, 4);
insert into suggestions (sugId, description, therapistId, userId) values (10005, 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis', 105, 5);
insert into suggestions (sugId, description, therapistId, userId) values (10006, 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis', 106, 6);
insert into suggestions (sugId, description, therapistId, userId) values (10007, 'sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan', 107, 7);
insert into suggestions (sugId, description, therapistId, userId) values (10008, 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus', 108, 8);
insert into suggestions (sugId, description, therapistId, userId) values (10009, null, 109, 9);
insert into suggestions (sugId, description, therapistId, userId) values (10010, 'phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus', 110, 10);
insert into suggestions (sugId, description, therapistId, userId) values (10011, null, 111, 11);
insert into suggestions (sugId, description, therapistId, userId) values (10012, 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 112, 12);
insert into suggestions (sugId, description, therapistId, userId) values (10013, 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas', 113, 13);
insert into suggestions (sugId, description, therapistId, userId) values (10014, null, 114, 14);
insert into suggestions (sugId, description, therapistId, userId) values (10015, 'purus phasellus in felis donec semper sapien a libero nam dui proin leo odio', 115, 15);
insert into suggestions (sugId, description, therapistId, userId) values (10016, 'ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', 116, 16);
insert into suggestions (sugId, description, therapistId, userId) values (10017, 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet', 117, 17);
insert into suggestions (sugId, description, therapistId, userId) values (10018, null, 118, 18);
insert into suggestions (sugId, description, therapistId, userId) values (10019, 'est quam pharetra magna ac consequat metus sapien ut nunc', 119, 19);
insert into suggestions (sugId, description, therapistId, userId) values (10020, null, 120, 20);
insert into suggestions (sugId, description, therapistId, userId) values (10021, 'lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet', 121, 21);
insert into suggestions (sugId, description, therapistId, userId) values (10022, 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec', 122, 22);
insert into suggestions (sugId, description, therapistId, userId) values (10023, 'porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit', 123, 23);
insert into suggestions (sugId, description, therapistId, userId) values (10024, 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus', 124, 24);
insert into suggestions (sugId, description, therapistId, userId) values (10025, 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 125, 25);
insert into suggestions (sugId, description, therapistId, userId) values (10026, 'ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 126, 26);
insert into suggestions (sugId, description, therapistId, userId) values (10027, 'eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim', null, 27);
insert into suggestions (sugId, description, therapistId, userId) values (10028, 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede', null, 28);
insert into suggestions (sugId, description, therapistId, userId) values (10029, 'a libero nam dui proin leo odio porttitor id consequat in consequat', 129, 29);
insert into suggestions (sugId, description, therapistId, userId) values (10030, 'erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis', 130, 30);
insert into suggestions (sugId, description, therapistId, userId) values (10031, 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', 131, 31);
insert into suggestions (sugId, description, therapistId, userId) values (10032, 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam', 132, 32);
insert into suggestions (sugId, description, therapistId, userId) values (10033, null, 133, 33);
insert into suggestions (sugId, description, therapistId, userId) values (10034, 'at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', 134, 34);
insert into suggestions (sugId, description, therapistId, userId) values (10035, 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', 135, 35);
insert into suggestions (sugId, description, therapistId, userId) values (10036, null, 136, 36);
insert into suggestions (sugId, description, therapistId, userId) values (10037, 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', 137, 37);
insert into suggestions (sugId, description, therapistId, userId) values (10038, 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum', 138, 38);
insert into suggestions (sugId, description, therapistId, userId) values (10039, null, 139, 39);
insert into suggestions (sugId, description, therapistId, userId) values (10040, 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue', 140, 40);
insert into suggestions (sugId, description, therapistId, userId) values (10041, null, 141, 41);
insert into suggestions (sugId, description, therapistId, userId) values (10042, 'arcu sed augue aliquam erat volutpat in congue etiam justo', 142, 42);
insert into suggestions (sugId, description, therapistId, userId) values (10043, 'felis ut at dolor quis odio consequat varius integer ac leo', 143, 43);
insert into suggestions (sugId, description, therapistId, userId) values (10044, null, 144, 44);
insert into suggestions (sugId, description, therapistId, userId) values (10045, 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed', 145, 45);
insert into suggestions (sugId, description, therapistId, userId) values (10046, 'cursus id turpis integer aliquet massa id lobortis convallis tortor', 146, 46);
insert into suggestions (sugId, description, therapistId, userId) values (10047, 'in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id', 147, 47);
insert into suggestions (sugId, description, therapistId, userId) values (10048, null, 148, 48);
insert into suggestions (sugId, description, therapistId, userId) values (10049, 'dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 149, 49);
insert into suggestions (sugId, description, therapistId, userId) values (10050, 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat', 150, 50);
insert into suggestions (sugId, description, therapistId, userId) values (10051, null, 151, 51);
insert into suggestions (sugId, description, therapistId, userId) values (10052, 'consequat lectus in est risus auctor sed tristique in tempus sit amet', 152, 52);
insert into suggestions (sugId, description, therapistId, userId) values (10053, 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', null, 53);
insert into suggestions (sugId, description, therapistId, userId) values (10054, 'justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas', 154, 54);
insert into suggestions (sugId, description, therapistId, userId) values (10055, 'sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu', 155, 55);
insert into suggestions (sugId, description, therapistId, userId) values (10056, 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis', null, 56);
insert into suggestions (sugId, description, therapistId, userId) values (10057, 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien', null, 57);
insert into suggestions (sugId, description, therapistId, userId) values (10058, 'phasellus sit amet erat nulla tempus vivamus in felis eu sapien', 158, 58);
insert into suggestions (sugId, description, therapistId, userId) values (10059, null, 159, 59);
insert into suggestions (sugId, description, therapistId, userId) values (10060, null, 160, 60);
insert into suggestions (sugId, description, therapistId, userId) values (10061, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio', 161, 61);
insert into suggestions (sugId, description, therapistId, userId) values (10062, null, 162, 62);
insert into suggestions (sugId, description, therapistId, userId) values (10063, 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 163, 63);
insert into suggestions (sugId, description, therapistId, userId) values (10064, 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue', 164, 64);
insert into suggestions (sugId, description, therapistId, userId) values (10065, 'consequat in consequat ut nulla sed accumsan felis ut at', 165, 65);
insert into suggestions (sugId, description, therapistId, userId) values (10066, 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor', 166, 66);
insert into suggestions (sugId, description, therapistId, userId) values (10067, 'accumsan felis ut at dolor quis odio consequat varius integer ac leo', 167, 67);
insert into suggestions (sugId, description, therapistId, userId) values (10068, 'lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt', 168, 68);
insert into suggestions (sugId, description, therapistId, userId) values (10069, 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 169, 69);
insert into suggestions (sugId, description, therapistId, userId) values (10070, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum', 170, 70);
insert into suggestions (sugId, description, therapistId, userId) values (10071, 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi', 171, 71);
insert into suggestions (sugId, description, therapistId, userId) values (10072, 'dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in', null, 72);
insert into suggestions (sugId, description, therapistId, userId) values (10073, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti', 173, 73);
insert into suggestions (sugId, description, therapistId, userId) values (10074, null, 174, 74);
insert into suggestions (sugId, description, therapistId, userId) values (10075, null, null, 75);
insert into suggestions (sugId, description, therapistId, userId) values (10076, 'at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam', 176, 76);
insert into suggestions (sugId, description, therapistId, userId) values (10077, 'dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non', 177, 77);
insert into suggestions (sugId, description, therapistId, userId) values (10078, 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie', 178, 78);
insert into suggestions (sugId, description, therapistId, userId) values (10079, null, 179, 79);
insert into suggestions (sugId, description, therapistId, userId) values (10080, 'eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin', 180, 80);
insert into suggestions (sugId, description, therapistId, userId) values (10081, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis', 181, 81);
insert into suggestions (sugId, description, therapistId, userId) values (10082, 'sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse', null, 82);
insert into suggestions (sugId, description, therapistId, userId) values (10083, 'nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit', 183, 83);
insert into suggestions (sugId, description, therapistId, userId) values (10084, 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 184, 84);
insert into suggestions (sugId, description, therapistId, userId) values (10085, 'erat quisque erat eros viverra eget congue eget semper rutrum', 185, 85);
insert into suggestions (sugId, description, therapistId, userId) values (10086, 'ut massa volutpat convallis morbi odio odio elementum eu interdum', 186, 86);
insert into suggestions (sugId, description, therapistId, userId) values (10087, null, 187, 87);
insert into suggestions (sugId, description, therapistId, userId) values (10088, 'eu felis fusce posuere felis sed lacus morbi sem mauris laoreet', 188, 88);
insert into suggestions (sugId, description, therapistId, userId) values (10089, null, null, 89);
insert into suggestions (sugId, description, therapistId, userId) values (10090, null, 190, 90);
insert into suggestions (sugId, description, therapistId, userId) values (10091, 'etiam pretium iaculis justo in hac habitasse platea dictumst etiam', 191, 91);
insert into suggestions (sugId, description, therapistId, userId) values (10092, 'nulla ut erat id mauris vulputate elementum nullam varius nulla', 192, 92);
insert into suggestions (sugId, description, therapistId, userId) values (10093, 'rutrum neque aenean auctor gravida sem praesent id massa id nisl', 193, 93);
insert into suggestions (sugId, description, therapistId, userId) values (10094, 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy', 194, 94);
insert into suggestions (sugId, description, therapistId, userId) values (10095, 'dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam', 195, 95);
insert into suggestions (sugId, description, therapistId, userId) values (10096, null, null, 96);
insert into suggestions (sugId, description, therapistId, userId) values (10097, 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl', 197, 97);
insert into suggestions (sugId, description, therapistId, userId) values (10098, 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', 198, 98);
insert into suggestions (sugId, description, therapistId, userId) values (10099, null, 199, 99);
insert into suggestions (sugId, description, therapistId, userId) values (10100, 'dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at', 200, 100);
insert into suggestions (sugId, description, therapistId, userId) values (10101, 'arcu sed augue aliquam erat volutpat in congue etiam justo', 201, 101);
insert into suggestions (sugId, description, therapistId, userId) values (10102, null, null, 102);
insert into suggestions (sugId, description, therapistId, userId) values (10103, null, 203, 103);
insert into suggestions (sugId, description, therapistId, userId) values (10104, 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', 204, 104);
insert into suggestions (sugId, description, therapistId, userId) values (10105, 'nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum', 205, 105);
insert into suggestions (sugId, description, therapistId, userId) values (10106, 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 206, 106);
insert into suggestions (sugId, description, therapistId, userId) values (10107, 'donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum', null, 107);
insert into suggestions (sugId, description, therapistId, userId) values (10108, null, 208, 108);
insert into suggestions (sugId, description, therapistId, userId) values (10109, 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris', 209, 109);
insert into suggestions (sugId, description, therapistId, userId) values (10110, null, 210, 110);
insert into suggestions (sugId, description, therapistId, userId) values (10111, 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet', 211, 111);
insert into suggestions (sugId, description, therapistId, userId) values (10112, 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem', null, 112);
insert into suggestions (sugId, description, therapistId, userId) values (10113, 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem', 213, 113);
insert into suggestions (sugId, description, therapistId, userId) values (10114, 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', 214, 114);
insert into suggestions (sugId, description, therapistId, userId) values (10115, 'dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse', 215, 115);
insert into suggestions (sugId, description, therapistId, userId) values (10116, 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui', 216, 116);
insert into suggestions (sugId, description, therapistId, userId) values (10117, 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a', 217, 117);
insert into suggestions (sugId, description, therapistId, userId) values (10118, 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis', 218, 118);
insert into suggestions (sugId, description, therapistId, userId) values (10119, null, 219, 119);
insert into suggestions (sugId, description, therapistId, userId) values (10120, null, 220, 120);
insert into suggestions (sugId, description, therapistId, userId) values (10121, null, 221, 121);
insert into suggestions (sugId, description, therapistId, userId) values (10122, 'dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam', 222, 122);
insert into suggestions (sugId, description, therapistId, userId) values (10123, 'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis', null, 123);
insert into suggestions (sugId, description, therapistId, userId) values (10124, null, 224, 124);
insert into suggestions (sugId, description, therapistId, userId) values (10125, 'luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', 225, 125);
insert into suggestions (sugId, description, therapistId, userId) values (10126, 'porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', 226, 126);
insert into suggestions (sugId, description, therapistId, userId) values (10127, 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', 227, 127);
insert into suggestions (sugId, description, therapistId, userId) values (10128, 'in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer', null, 128);
insert into suggestions (sugId, description, therapistId, userId) values (10129, null, 229, 129);
insert into suggestions (sugId, description, therapistId, userId) values (10130, 'magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 230, 130);
insert into suggestions (sugId, description, therapistId, userId) values (10131, null, 231, 131);
insert into suggestions (sugId, description, therapistId, userId) values (10132, null, 232, 132);
insert into suggestions (sugId, description, therapistId, userId) values (10133, null, 233, 133);
insert into suggestions (sugId, description, therapistId, userId) values (10134, null, 234, 134);
insert into suggestions (sugId, description, therapistId, userId) values (10135, 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 235, 135);
insert into suggestions (sugId, description, therapistId, userId) values (10136, 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet', 236, 136);
insert into suggestions (sugId, description, therapistId, userId) values (10137, 'ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus', 237, 137);
insert into suggestions (sugId, description, therapistId, userId) values (10138, null, 238, 138);
insert into suggestions (sugId, description, therapistId, userId) values (10139, 'volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', 239, 139);
insert into suggestions (sugId, description, therapistId, userId) values (10140, 'nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim', 240, 140);
insert into suggestions (sugId, description, therapistId, userId) values (10141, 'et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', 241, 141);
insert into suggestions (sugId, description, therapistId, userId) values (10142, 'sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 242, 142);
insert into suggestions (sugId, description, therapistId, userId) values (10143, null, 243, 143);
insert into suggestions (sugId, description, therapistId, userId) values (10144, 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 244, 144);
insert into suggestions (sugId, description, therapistId, userId) values (10145, 'ornare consequat lectus in est risus auctor sed tristique in tempus', 245, 145);
insert into suggestions (sugId, description, therapistId, userId) values (10146, 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor', 246, 146);
insert into suggestions (sugId, description, therapistId, userId) values (10147, null, 247, 147);
insert into suggestions (sugId, description, therapistId, userId) values (10148, 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 248, 148);
insert into suggestions (sugId, description, therapistId, userId) values (10149, 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst', 249, 149);
insert into suggestions (sugId, description, therapistId, userId) values (10150, 'dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', 250, 150);
insert into suggestions (sugId, description, therapistId, userId) values (10151, 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus', 251, 151);
insert into suggestions (sugId, description, therapistId, userId) values (10152, 'eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper', 252, 152);
insert into suggestions (sugId, description, therapistId, userId) values (10153, 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque', 253, 153);
insert into suggestions (sugId, description, therapistId, userId) values (10154, 'erat vestibulum sed magna at nunc commodo placerat praesent blandit', 254, 154);
insert into suggestions (sugId, description, therapistId, userId) values (10155, 'lobortis ligula sit amet eleifend pede libero quis orci nullam molestie', 255, 155);
insert into suggestions (sugId, description, therapistId, userId) values (10156, 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 256, 156);
insert into suggestions (sugId, description, therapistId, userId) values (10157, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante', 257, 157);
insert into suggestions (sugId, description, therapistId, userId) values (10158, 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo', 258, 158);
insert into suggestions (sugId, description, therapistId, userId) values (10159, null, 259, 159);
insert into suggestions (sugId, description, therapistId, userId) values (10160, 'dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', null, 160);
insert into suggestions (sugId, description, therapistId, userId) values (10161, 'rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit', 261, 161);
insert into suggestions (sugId, description, therapistId, userId) values (10162, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor', 262, 162);
insert into suggestions (sugId, description, therapistId, userId) values (10163, null, 263, 163);
insert into suggestions (sugId, description, therapistId, userId) values (10164, 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor', 264, 164);
insert into suggestions (sugId, description, therapistId, userId) values (10165, null, 265, 165);
insert into suggestions (sugId, description, therapistId, userId) values (10166, 'fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 266, 166);
insert into suggestions (sugId, description, therapistId, userId) values (10167, 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante', 267, 167);
insert into suggestions (sugId, description, therapistId, userId) values (10168, null, 268, 168);
insert into suggestions (sugId, description, therapistId, userId) values (10169, 'congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus', null, 169);
insert into suggestions (sugId, description, therapistId, userId) values (10170, 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 270, 170);
insert into suggestions (sugId, description, therapistId, userId) values (10171, null, 271, 171);
insert into suggestions (sugId, description, therapistId, userId) values (10172, 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum', 272, 172);
insert into suggestions (sugId, description, therapistId, userId) values (10173, 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin', 273, 173);
insert into suggestions (sugId, description, therapistId, userId) values (10174, 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', null, 174);
insert into suggestions (sugId, description, therapistId, userId) values (10175, 'duis ac nibh fusce lacus purus aliquet at feugiat non', 275, 175);
insert into suggestions (sugId, description, therapistId, userId) values (10176, 'congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 276, 176);
insert into suggestions (sugId, description, therapistId, userId) values (10177, null, null, 177);
insert into suggestions (sugId, description, therapistId, userId) values (10178, 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', 278, 178);
insert into suggestions (sugId, description, therapistId, userId) values (10179, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 279, 179);
insert into suggestions (sugId, description, therapistId, userId) values (10180, 'nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut', 280, 180);
insert into suggestions (sugId, description, therapistId, userId) values (10181, 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero', 281, 181);
insert into suggestions (sugId, description, therapistId, userId) values (10182, 'dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum', 282, 182);
insert into suggestions (sugId, description, therapistId, userId) values (10183, 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue', 283, 183);
insert into suggestions (sugId, description, therapistId, userId) values (10184, 'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel', 284, 184);
insert into suggestions (sugId, description, therapistId, userId) values (10185, 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in', null, 185);
insert into suggestions (sugId, description, therapistId, userId) values (10186, 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros', null, 186);
insert into suggestions (sugId, description, therapistId, userId) values (10187, 'eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie', 287, 187);
insert into suggestions (sugId, description, therapistId, userId) values (10188, 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 288, 188);
insert into suggestions (sugId, description, therapistId, userId) values (10189, 'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 289, 189);
insert into suggestions (sugId, description, therapistId, userId) values (10190, 'luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 290, 190);
insert into suggestions (sugId, description, therapistId, userId) values (10191, 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus', null, 191);
insert into suggestions (sugId, description, therapistId, userId) values (10192, 'est congue elementum in hac habitasse platea dictumst morbi vestibulum velit', 292, 192);
insert into suggestions (sugId, description, therapistId, userId) values (10193, 'posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 293, 193);
insert into suggestions (sugId, description, therapistId, userId) values (10194, null, 294, 194);
insert into suggestions (sugId, description, therapistId, userId) values (10195, 'est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et', 295, 195);
insert into suggestions (sugId, description, therapistId, userId) values (10196, 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero', 296, 196);
insert into suggestions (sugId, description, therapistId, userId) values (10197, null, 297, 197);
insert into suggestions (sugId, description, therapistId, userId) values (10198, 'id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', 298, 198);
insert into suggestions (sugId, description, therapistId, userId) values (10199, 'elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur', 299, 199);
insert into suggestions (sugId, description, therapistId, userId) values (10200, 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', 300, 200);
